/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: trzyde.com (https://sketchfab.com/trzyde.com)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/room-test-7x9-b6732e51043c4d178edb399e8dd8c031
title: Room_Test_7x9_
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Bricks(props) {
  const { nodes, materials } = useGLTF("/env_bricks.gltf");
  return (
    <group scale={[0.05, 0.08, 0.05]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Model_7x9_UV_Modeling_Mat_0.geometry}
              material={materials.Modeling_Mat}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/env_bricks.gltf");
