/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Yo.Ri (https://sketchfab.com/grox777)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vr-gallery-vintage-for-product-showcase-2019-c0c76fac78774481b8322c775a58c711
title: VR Gallery vintage For Product Showcase 2019
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Vintage(props) {
  const { nodes, materials } = useGLTF("/env_vintage.gltf");
  return (
    <group scale={[0.08, 0.08, 0.08]} rotation={[0,Math.PI/2,0]} position={[0,0,13]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 50, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={50}
          >
            <mesh
              geometry={nodes.ShowCase_Gallery_Walls_0.geometry}
              material={materials.Walls}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_wood_0.geometry}
              material={materials.wood}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_Gray_0.geometry}
              material={materials.Gray}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_Bricks_0.geometry}
              material={materials.Bricks}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_black_0.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_Floor_0.geometry}
              material={materials.Floor}
            />
            <mesh
              geometry={nodes.ShowCase_Gallery_Glass_0.geometry}
              material={materials.Glass}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/env_vintage.gltf");
