/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aaron Openshaw (https://sketchfab.com/aaronopenshaw)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spatial-fade-carbon-carpet-plank-vr-experience-2f1d0bd08c9c43d8a2a89b9915817dde
title: Spatial Fade Carbon Carpet Plank VR Experience
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Warehouse(props) {
  const { nodes, materials } = useGLTF("/env_warehouse.gltf");
  return (
    <group {...props} position={[-47,0,95]} scale={[3,3,3]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <lineSegments
          geometry={nodes.Material6.geometry}
          material={materials.edge_color979991255}
        />
        <lineSegments
          geometry={nodes.Material4.geometry}
          material={materials.edge_color255248248255}
        />
        <lineSegments
          geometry={nodes.Material4_1.geometry}
          material={materials.edge_color000255}
        />
        <lineSegments
          geometry={nodes.Material3.geometry}
          material={materials.edge_color000255}
        />
        <lineSegments
          geometry={nodes.Material4_2.geometry}
          material={materials.edge_color116119113255}
        />
        <lineSegments
          geometry={nodes.Material4_3.geometry}
          material={materials.edge_color200200200255}
        />
        <mesh
          geometry={nodes.Material2.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Material2_1.geometry}
          material={materials.Structure}
        />
        <mesh
          geometry={nodes.Material2_2.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Material2_3.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Material2_4.geometry}
          material={materials.Long_Walls}
        />
        <mesh
          geometry={nodes.Material2_5.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Material2_6.geometry}
          material={materials.Walls}
        />
        <mesh
          geometry={nodes.Material2_7.geometry}
          material={materials.Wall_Horizon}
        />
        <mesh
          geometry={nodes.Material2_8.geometry}
          material={materials.Red_Lamp}
        />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.Grey} />
      </group>
    </group>
  );
}

// useGLTF.preload("/env_warehouse.gltf");
