/* eslint-disable react/no-unknown-property */
/* eslint-disable react/no-children-prop */
/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Apophisie (https://sketchfab.com/Apophisie)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lustre-luxe-29392dd175444772881f62436af56397
title: Lustre Luxe
*/

import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo, useRef } from "react";
import { useBoolean } from "react-use";
import ObjectTransformControls from "../components/ObjectTransformControls";
import { useSceneObjects } from "../store/useSceneObjects";
import { useUpdateObjectPosition } from "../utils/hooks";

const context = createContext();
export function ChandelierInstances({ children, ...props }) {
  const { nodes } = useGLTF("/chandelier-transformed.glb");
  const instances = useMemo(
    () => ({
      CircleMaterial: nodes["Circle002_Material_#49_0"],
      ConeMaterial: nodes["Cone001_Material_#49_0"],
      ObjectMaterial: nodes["Object127_Material_#49_0"],
      GeoSphereMaterial: nodes["GeoSphere001_Material_#50_0"],
      GeoSphereMaterial1: nodes["GeoSphere807_Material_#50_0"],
      GeoSphereMaterial2: nodes["GeoSphere808_Material_#50_0"],
      GeoSphereMaterial3: nodes["GeoSphere793_Material_#50_0"],
      GeoSphereMaterial4: nodes["GeoSphere806_Material_#50_0"],
      Line: nodes.Line089__0,
      LineMaterial: nodes["Line107_Material_#50_0"],
      GeoSphereMaterial5: nodes["GeoSphere045_Material_#50_0"],
      GeoSphereMaterial6: nodes["GeoSphere047_Material_#50_0"],
      GeoSphereMaterial7: nodes["GeoSphere048_Material_#50_0"],
      GeoSphereMaterial8: nodes["GeoSphere051_Material_#50_0"],
      GeoSphereMaterial9: nodes["GeoSphere052_Material_#50_0"],
      GeoSphereMaterial10: nodes["GeoSphere054_Material_#50_0"],
      GeoSphereMaterial11: nodes["GeoSphere057_Material_#50_0"],
      GeoSphereMaterial12: nodes["GeoSphere059_Material_#50_0"],
      GeoSphereMaterial13: nodes["GeoSphere061_Material_#50_0"],
      GeoSphereMaterial14: nodes["GeoSphere062_Material_#50_0"],
      GeoSphereMaterial15: nodes["GeoSphere064_Material_#50_0"],
      GeoSphereMaterial16: nodes["GeoSphere066_Material_#50_0"],
      GeoSphereMaterial17: nodes["GeoSphere068_Material_#50_0"],
      GeoSphereMaterial18: nodes["GeoSphere070_Material_#50_0"],
      GeoSphereMaterial19: nodes["GeoSphere072_Material_#50_0"],
      GeoSphereMaterial20: nodes["GeoSphere074_Material_#50_0"],
      GeoSphereMaterial21: nodes["GeoSphere075_Material_#50_0"],
      GeoSphereMaterial22: nodes["GeoSphere076_Material_#50_0"],
      GeoSphereMaterial23: nodes["GeoSphere077_Material_#50_0"],
      GeoSphereMaterial24: nodes["GeoSphere078_Material_#50_0"],
      GeoSphereMaterial25: nodes["GeoSphere079_Material_#50_0"],
      GeoSphereMaterial26: nodes["GeoSphere081_Material_#50_0"],
      GeoSphereMaterial27: nodes["GeoSphere102_Material_#50_0"],
      GeoSphereMaterial28: nodes["GeoSphere164_Material_#50_0"],
      GeoSphereMaterial29: nodes["GeoSphere444_Material_#50_0"],
      GeoSphereMaterial30: nodes["GeoSphere469_Material_#50_0"],
      GeoSphereMaterial31: nodes["GeoSphere482_Material_#50_0"],
      GeoSphereMaterial32: nodes["GeoSphere508_Material_#50_0"],
      GeoSphereMaterial33: nodes["GeoSphere535_Material_#50_0"],
      GeoSphereMaterial34: nodes["GeoSphere571_Material_#50_0"],
      GeoSphereMaterial35: nodes["GeoSphere609_Material_#50_0"],
      GeoSphereMaterial36: nodes["GeoSphere647_Material_#50_0"],
      GeoSphereMaterial37: nodes["GeoSphere649_Material_#50_0"],
      GeoSphereMaterial38: nodes["GeoSphere688_Material_#50_0"],
      GeoSphereMaterial39: nodes["GeoSphere726_Material_#50_0"],
      GeoSphereMaterial40: nodes["GeoSphere792_Material_#50_0"],
      GeoSphereMaterial41: nodes["GeoSphere796_Material_#50_0"],
      GeoSphereMaterial42: nodes["GeoSphere798_Material_#50_0"],
      GeoSphereMaterial43: nodes["GeoSphere799_Material_#50_0"],
      GeoSphereMaterial44: nodes["GeoSphere800_Material_#50_0"],
      GeoSphereMaterial45: nodes["GeoSphere801_Material_#50_0"],
      GeoSphereMaterial46: nodes["GeoSphere802_Material_#50_0"],
      GeoSphereMaterial47: nodes["GeoSphere803_Material_#50_0"],
      GeoSphereMaterial48: nodes["GeoSphere804_Material_#50_0"],
      GeoSphereMaterial49: nodes["GeoSphere805_Material_#50_0"],
      GeoSphereMaterial50: nodes["GeoSphere810_Material_#50_0"],
      GeoSphereMaterial51: nodes["GeoSphere811_Material_#50_0"],
      GeoSphereMaterial52: nodes["GeoSphere813_Material_#50_0"],
      GeoSphereMaterial53: nodes["GeoSphere815_Material_#50_0"],
      GeoSphereMaterial54: nodes["GeoSphere817_Material_#50_0"],
      GeoSphereMaterial55: nodes["GeoSphere819_Material_#50_0"],
      GeoSphereMaterial56: nodes["GeoSphere855_Material_#50_0"],
      GeoSphereMaterial57: nodes["GeoSphere857_Material_#50_0"],
      GeoSphereMaterial58: nodes["GeoSphere859_Material_#50_0"],
      GeoSphereMaterial59: nodes["GeoSphere861_Material_#50_0"],
      GeoSphereMaterial60: nodes["GeoSphere1270_Material_#50_0"],
      GeoSphereMaterial61: nodes["GeoSphere1290_Material_#50_0"],
      GeoSphereMaterial62: nodes["GeoSphere1312_Material_#50_0"],
      GeoSphereMaterial63: nodes["GeoSphere1337_Material_#50_0"],
      GeoSphereMaterial64: nodes["GeoSphere1361_Material_#50_0"],
      GeoSphereMaterial65: nodes["GeoSphere1388_Material_#50_0"],
      GeoSphereMaterial66: nodes["GeoSphere1414_Material_#50_0"],
      GeoSphereMaterial67: nodes["GeoSphere1438_Material_#50_0"],
      GeoSphereMaterial68: nodes["GeoSphere1463_Material_#50_0"],
      GeoSphereMaterial69: nodes["GeoSphere1490_Material_#50_0"],
      GeoSphereMaterial70: nodes["GeoSphere1540_Material_#50_0"],
      GeoSphereMaterial71: nodes["GeoSphere1547_Material_#50_0"],
      BougeoiresMaterial: nodes["Bougeoires_Material_#49_0"],
      BougiescireMaterial: nodes["Bougies_cire_Material_#51_0"],
      BougiesflammeMaterial: nodes["Bougies_flamme_Material_#52_0"],
      CylinderMaterial: nodes["Cylinder004_Material_#49_0"],
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Chandelier(props) {
  const instances = useContext(context);

  const [active, toggleActive] = useBoolean(false);
  const [localPosition, setLocalPosition] = React.useState(props.position);
  const { updateObjectPosition } = useSceneObjects();
  const objectRef = useRef();

  useUpdateObjectPosition(props.id, localPosition, updateObjectPosition);

  return (
    <>
      <group
        {...props}
        dispose={null}
        onClick={() => {
          toggleActive();
        }}
        onPointerMissed={(e) => {
          e.type === "click" && toggleActive(false);
        }}
        ref={objectRef}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[-0.01, 0.78, 0.01]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <group position={[0.01, 0.01, 1.9]} scale={[0.27, 0.27, 2.21]}>
                <instances.CircleMaterial />
              </group>
              <group position={[0.01, 0, 2.62]} scale={0.24}>
                <instances.ConeMaterial />
              </group>
              <group position={[0.01, 0.01, -0.78]} scale={[1, 1, 1.88]}>
                <instances.ObjectMaterial />
              </group>
              <group
                position={[0.01, 0.01, -2.22]}
                rotation={[-Math.PI / 2, -1.4, 0]}
              >
                <group position={[-1.54, -1.29, 0]}>
                  <instances.GeoSphereMaterial />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -0.78]}
                rotation={[Math.PI / 2, 0.87, Math.PI / 2]}
                scale={1.43}
              >
                <group
                  position={[0.01, 1.02, 0]}
                  rotation={[-2.44, Math.PI / 2, 0]}
                  scale={0.05}
                >
                  <instances.GeoSphereMaterial1 />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -0.78]}
                rotation={[Math.PI / 2, 0.7, Math.PI / 2]}
                scale={1.43}
              >
                <group
                  position={[0.01, 1.02, 0]}
                  rotation={[-2.27, Math.PI / 2, 0]}
                  scale={0.05}
                >
                  <instances.GeoSphereMaterial2 />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -0.78]}
                rotation={[Math.PI / 2, Math.PI / 6, Math.PI / 2]}
                scale={1.43}
              >
                <group
                  position={[0.02, 1.01, 0]}
                  rotation={[-2.09, Math.PI / 2, 0]}
                  scale={0.05}
                >
                  <instances.GeoSphereMaterial3 />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -0.78]}
                rotation={[Math.PI / 2, Math.PI / 3, Math.PI / 2]}
                scale={1.43}
              >
                <group
                  position={[0.01, 1.02, 0]}
                  rotation={[-2.62, Math.PI / 2, 0]}
                  scale={0.05}
                >
                  <instances.GeoSphereMaterial4 />
                </group>
              </group>
              <group
                position={[-1.56, -1.56, 0.54]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.Line />
                </group>
              </group>
              <group
                position={[-1.56, 1.58, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group position={[0.01, -0.44, -2.2]} scale={0.07}>
                <instances.GeoSphereMaterial5 />
              </group>
              <group position={[0.54, -1.44, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial6 />
              </group>
              <group position={[0.78, -1.33, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial7 />
              </group>
              <group position={[1.19, -0.99, -0.93]} scale={0.07}>
                <instances.GeoSphereMaterial8 />
              </group>
              <group position={[1.34, -0.76, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial9 />
              </group>
              <group position={[1.53, -0.26, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial10 />
              </group>
              <group position={[1.46, 0.54, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial11 />
              </group>
              <group position={[1.19, 1, -0.93]} scale={0.07}>
                <instances.GeoSphereMaterial12 />
              </group>
              <group position={[0.78, 1.34, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial13 />
              </group>
              <group position={[0.54, 1.46, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial14 />
              </group>
              <group position={[0.01, 1.55, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial15 />
              </group>
              <group position={[-0.52, 1.46, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial16 />
              </group>
              <group position={[-0.98, 1.19, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial17 />
              </group>
              <group position={[-1.33, 0.78, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial18 />
              </group>
              <group position={[-1.51, 0.28, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial19 />
              </group>
              <group position={[-1.51, -0.26, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial20 />
              </group>
              <group position={[-1.44, -0.52, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial21 />
              </group>
              <group position={[-1.33, -0.76, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial22 />
              </group>
              <group position={[-1.18, -0.98, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial23 />
              </group>
              <group position={[-0.98, -1.18, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial24 />
              </group>
              <group position={[-0.76, -1.33, -0.93]} scale={0.07}>
                <instances.GeoSphereMaterial25 />
              </group>
              <group position={[-0.52, -1.44, -0.92]} scale={0.07}>
                <instances.GeoSphereMaterial26 />
              </group>
              <group position={[0.08, -0.38, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial27 />
              </group>
              <group position={[0.3, -0.34, -2.2]} scale={0.07}>
                <instances.GeoSphereMaterial28 />
              </group>
              <group position={[0.38, -0.13, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial29 />
              </group>
              <group position={[0.45, 0.01, -2.2]} scale={0.07}>
                <instances.GeoSphereMaterial30 />
              </group>
              <group position={[0.4, 0.08, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial31 />
              </group>
              <group position={[0.36, 0.21, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial32 />
              </group>
              <group position={[0.29, 0.34, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial33 />
              </group>
              <group position={[0.08, 0.44, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial34 />
              </group>
              <group position={[-0.06, 0.4, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial35 />
              </group>
              <group position={[-0.2, 0.37, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial36 />
              </group>
              <group position={[-0.31, 0.27, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial37 />
              </group>
              <group position={[-0.39, 0.15, -2.21]} scale={0.07}>
                <instances.GeoSphereMaterial38 />
              </group>
              <group position={[-0.44, 0.01, -2.2]} scale={0.07}>
                <instances.GeoSphereMaterial39 />
              </group>
              <group position={[-1.35, -0.49, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial40 />
              </group>
              <group position={[1.36, -0.49, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial41 />
              </group>
              <group position={[1.12, -0.93, -0.76]} scale={0.07}>
                <instances.GeoSphereMaterial42 />
              </group>
              <group position={[0.94, -1.1, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial43 />
              </group>
              <group position={[0.73, -1.24, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial44 />
              </group>
              <group position={[0.5, -1.35, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial45 />
              </group>
              <group position={[0.26, -1.41, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial46 />
              </group>
              <group position={[0.01, -1.45, -0.76]} scale={0.07}>
                <instances.GeoSphereMaterial47 />
              </group>
              <group position={[-0.24, -1.42, -0.76]} scale={0.07}>
                <instances.GeoSphereMaterial48 />
              </group>
              <group position={[-0.49, -1.36, -0.76]} scale={0.07}>
                <instances.GeoSphereMaterial49 />
              </group>
              <group position={[0.26, 1.44, -0.76]} scale={0.07}>
                <instances.GeoSphereMaterial50 />
              </group>
              <group position={[-0.24, 1.42, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial51 />
              </group>
              <group position={[-0.71, 1.26, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial52 />
              </group>
              <group position={[-1.1, 0.93, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial53 />
              </group>
              <group position={[-1.35, 0.5, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial54 />
              </group>
              <group position={[-1.44, 0.01, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial55 />
              </group>
              <group position={[0.73, 1.26, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial56 />
              </group>
              <group position={[1.11, 0.94, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial57 />
              </group>
              <group position={[1.36, 0.5, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial58 />
              </group>
              <group position={[1.45, 0.01, -0.75]} scale={0.07}>
                <instances.GeoSphereMaterial59 />
              </group>
              <group position={[-0.41, -0.07, 1.72]} scale={0.07}>
                <instances.GeoSphereMaterial60 />
              </group>
              <group position={[-0.41, 0.08, 1.71]} scale={0.07}>
                <instances.GeoSphereMaterial61 />
              </group>
              <group position={[-0.36, 0.22, 1.73]} scale={0.07}>
                <instances.GeoSphereMaterial62 />
              </group>
              <group position={[-0.26, 0.33, 1.72]} scale={0.07}>
                <instances.GeoSphereMaterial63 />
              </group>
              <group position={[-0.14, 0.4, 1.67]} scale={0.07}>
                <instances.GeoSphereMaterial64 />
              </group>
              <group position={[0.01, 0.43, 1.71]} scale={0.07}>
                <instances.GeoSphereMaterial65 />
              </group>
              <group position={[0.15, 0.4, 1.71]} scale={0.07}>
                <instances.GeoSphereMaterial66 />
              </group>
              <group position={[0.28, 0.33, 1.73]} scale={0.07}>
                <instances.GeoSphereMaterial67 />
              </group>
              <group position={[0.37, 0.22, 1.7]} scale={0.07}>
                <instances.GeoSphereMaterial68 />
              </group>
              <group position={[0.42, 0.08, 1.74]} scale={0.07}>
                <instances.GeoSphereMaterial69 />
              </group>
              <group position={[0.42, -0.07, 1.73]} scale={0.07}>
                <instances.GeoSphereMaterial70 />
              </group>
              <group position={[0.37, -0.2, 1.7]} scale={0.07}>
                <instances.GeoSphereMaterial71 />
              </group>
              <group
                position={[1.58, 1.57, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[2.23, 0.01, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[-1.56, -1.56, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[0.01, -2.21, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[1.57, -1.56, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[-2.21, 0.01, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -0.85]}
                rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI / 2]}
                scale={0.97}
              >
                <group position={[0, 1.94, 0]}>
                  <instances.BougeoiresMaterial />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -1.19]}
                rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI / 2]}
                scale={0.97}
              >
                <group position={[0, 1.94, 0]}>
                  <instances.BougiescireMaterial />
                </group>
              </group>
              <group
                position={[0.01, 0.01, -1.19]}
                rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI / 2]}
                scale={0.97}
              >
                <group position={[0, 1.94, 0]}>
                  <instances.BougiesflammeMaterial />
                </group>
              </group>
              <group
                position={[0, -0.02, -1.73]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
                scale={1.31}
              >
                <group position={[0.65, 0.02, 0.21]}>
                  <instances.LineMaterial />
                </group>
              </group>
              <group position={[0.01, 0.01, -2.13]}>
                <instances.CylinderMaterial />
              </group>
              <group
                position={[0.01, 2.23, 0.2]}
                rotation={[Math.PI / 2, -0.96, -Math.PI / 2]}
              >
                <group position={[0.93, 0.04, 0.24]}>
                  <instances.LineMaterial />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      {active && (
        <ObjectTransformControls
          object={objectRef.current}
          setLocalPosition={() => setLocalPosition}
        />
      )}
    </>
  );
}

useGLTF.preload("/chandelier-transformed.glb");
