/* eslint-disable react/no-unknown-property */
/* eslint-disable react/no-children-prop */
/* eslint-disable react/prop-types */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo, useRef } from "react";
import { useToggle } from "react-use";
import ObjectTransformControls from "../components/ObjectTransformControls";
// import { useSceneObjects } from "../store/useSceneObjects";
import { sceneActions, sceneStateStore } from "../store/sceneData";

const context = createContext();

export function DiningSetInstances({ children, ...props }) {
  const { nodes } = useGLTF("/dining_set-transformed.glb");

  const instances = useMemo(
    () => ({
      Body: nodes.Body1__0,
      BodyPolyurethane: nodes.Body1_Polyurethane_0,
      BodyDMahoganyGlossy: nodes["Body38_3D_Mahogany_-_Glossy_0"],
      BodyMirror: nodes.Body42_Mirror_0,
      BodyGlassMediumColor: nodes["Body45_Glass_-_Medium_Color_0"],
      BodyDMahoganyGlossy1: nodes["Body46_3D_Mahogany_-_Glossy_0"],
      Body1: nodes.Body47__0,
      BodyPolyurethane1: nodes.Body47_Polyurethane_0,
      Body2: nodes.Body48__0,
      BodyPolyurethane2: nodes.Body48_Polyurethane_0,
      Body3: nodes.Body49__0,
      BodyPolyurethane3: nodes.Body49_Polyurethane_0,
      Body4: nodes.Body50__0,
      BodyPolyurethane4: nodes.Body50_Polyurethane_0,
      BodyOpaque: nodes["Body51_Opaque(152,170,175)_0"],
      BodyOpaque1: nodes["Body56_Opaque(152,170,175)_0"],
      BodyOpaque2: nodes["Body57_Opaque(152,170,175)_0"],
      BodyOpaque3: nodes["Body58_Opaque(152,170,175)_0"],
      BodyOpaque4: nodes["Body59_Opaque(152,170,175)_0"],
      BodyGlassLightColor: nodes["Body61_Glass_-_Light_Color_0"],
      BodyGlassLightColor1: nodes["Body62_Glass_-_Light_Color_0"],
      BodyGlassLightColor2: nodes["Body63_Glass_-_Light_Color_0"],
      BodyGlassLightColor3: nodes["Body64_Glass_-_Light_Color_0"],
      BodyGlassLightColor4: nodes["Body65_Glass_-_Light_Color_0"],
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function DiningSet(props) {
  const instances = useContext(context);

  const [active, toggleActive] = useToggle(false);

  const objectRef = useRef();

  return (
    <>
      <group
        {...props}
        dispose={null}
        onClick={(e) => {
          e.stopPropagation();
          // setActiveObject(props.objectId);
          // setActiveChildObject(props.objectId, e.object.uuid);
          // setTransformUpdate(true);
          sceneActions.setActiveObject(props.objectId);
          // console.log(e.object.instance.current.material.name)
          sceneActions.setActiveMaterial(
            e.object.instance.current.material.name
          );
          toggleActive(true);
        }}
        onPointerMissed={(e) => {
          e.type === "click" && toggleActive(false);
          sceneActions.removeActiveObject();
          console.log(sceneStateStore);
          // rmActiveObject(props.objectId);
          // setTransformUpdate(false);
        }}
        position={[0,0,0]}
        rotation={[0,0,0]}
        scale={[4,4,4]}
        ref={objectRef}
      >
        <instances.Body color={props.nodes.Body1__0} />
        <instances.BodyPolyurethane color={props.nodes.Polyurethane} />
        <instances.BodyDMahoganyGlossy
          color={props.nodes["3D_Mahogany_-_Glossy"]}
        />
        <instances.BodyMirror color={props.nodes.Mirror} />
        <instances.BodyGlassMediumColor
          color={props.nodes["Glass_-_Medium_Color"]}
        />
        <instances.BodyDMahoganyGlossy1
          color={props.nodes["3D_Mahogany_-_Glossy"]}
        />
        <instances.Body1 color={props.nodes.Body1__0} />
        <instances.BodyPolyurethane1 color={props.nodes.Polyurethane} />
        <instances.Body2 color={props.nodes.Body1__0} />
        <instances.BodyPolyurethane2 color={props.nodes.Polyurethane} />
        <instances.Body3 color={props.nodes.Body1__0} />
        <instances.BodyPolyurethane3 color={props.nodes.Polyurethane} />
        <instances.Body4 color={props.nodes.Body1__0} />
        <instances.BodyPolyurethane4 color={props.nodes.Polyurethane} />
        <instances.BodyOpaque color={props.nodes.Opaque152170175} />
        <instances.BodyOpaque1 color={props.nodes.Opaque152170175} />
        <instances.BodyOpaque2 color={props.nodes.Opaque152170175} />
        <instances.BodyOpaque3 color={props.nodes.Opaque152170175} />
        <instances.BodyOpaque4 color={props.nodes.Opaque152170175} />
        <instances.BodyGlassLightColor
          color={props.nodes["Glass_-_Light_Color"]}
        />
        <instances.BodyGlassLightColor1
          color={props.nodes["Glass_-_Light_Color"]}
        />
        <instances.BodyGlassLightColor2
          color={props.nodes["Glass_-_Light_Color"]}
        />
        <instances.BodyGlassLightColor3
          color={props.nodes["Glass_-_Light_Color"]}
        />
        <instances.BodyGlassLightColor4
          color={props.nodes["Glass_-_Light_Color"]}
        />
      </group>
      {active && (
        <ObjectTransformControls
          id={props.objectId}
          object={objectRef.current}
        />
      )}
    </>
  );
}

useGLTF.preload("/dining_set-transformed.glb");
