/* eslint-disable react/no-unknown-property */
/* eslint-disable react/no-children-prop */
/* eslint-disable react/prop-types */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cartti (https://sketchfab.com/cartti)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fairy-lights-82a67d28bc554f29b70c3300dc06bc3d
title: Fairy Lights
*/

import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo, useRef } from "react";
import { useBoolean } from "react-use";
import ObjectTransformControls from "../components/ObjectTransformControls";
import { useSceneObjects } from "../store/useSceneObjects";
import { useUpdateObjectPosition } from "../utils/hooks";

const context = createContext();
export function FairyLightsInstances({ children, ...props }) {
  const { nodes } = useGLTF("/fairy_lights-transformed.glb");
  const instances = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_5,
      Object2: nodes.Object_6,
      Object3: nodes.Object_7,
      Object4: nodes.Object_9,
      Object5: nodes.Object_10,
      Object6: nodes.Object_11,
      Object7: nodes.Object_12,
      Object8: nodes.Object_14,
      Object9: nodes.Object_15,
      Object10: nodes.Object_16,
      Object11: nodes.Object_17,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function FairyLights(props) {
  const instances = useContext(context);

  const [active, toggleActive] = useBoolean(false);
  const [localPosition, setLocalPosition] = React.useState(props.position);
  const { updateObjectPosition } = useSceneObjects();
  const objectRef = useRef();

  useUpdateObjectPosition(props.id, localPosition, updateObjectPosition);

  return (
    <>
      <group
        {...props}
        dispose={null}
        onClick={() => {
          toggleActive();
        }}
        onPointerMissed={(e) => {
          e.type === "click" && toggleActive(false);
        }}
        ref={objectRef}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-2.02, 0.68, 1]}>
              <instances.Object />
              <instances.Object1 />
              <instances.Object2 />
              <instances.Object3 />
            </group>
            <group position={[-2.02, 0.68, 0]}>
              <instances.Object4 />
              <instances.Object5 />
              <instances.Object6 />
              <instances.Object7 />
            </group>
            <group position={[-2.02, 0.68, -1]}>
              <instances.Object8 />
              <instances.Object9 />
              <instances.Object10 />
              <instances.Object11 />
            </group>
          </group>
        </group>
      </group>
      {active && (
        <ObjectTransformControls
          object={objectRef.current}
          setLocalPosition={() => setLocalPosition}
        />
      )}
    </>
  );
}

useGLTF.preload("/fairy_lights-transformed.glb");
