/* eslint-disable react/no-unknown-property */
/* eslint-disable react/no-children-prop */
/* eslint-disable react/prop-types */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo, useRef } from "react";
import { useBoolean } from "react-use";
import ObjectTransformControls from "../components/ObjectTransformControls";
import { useSceneObjects } from "../store/useSceneObjects";
import { useUpdateObjectPosition } from "../utils/hooks";

const context = createContext();
export function ModernChairInstances({ children, ...props }) {
  const { nodes } = useGLTF("/modern_chair-transformed.glb");
  const instances = useMemo(
    () => ({
      Object: nodes.Object_2,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function ModernChair(props) {
  const instances = useContext(context);

  const [active, toggleActive] = useBoolean(false);
  const [localPosition, setLocalPosition] = React.useState(props.position);
  const { updateObjectPosition } = useSceneObjects();
  const objectRef = useRef();

  useUpdateObjectPosition(props.id, localPosition, updateObjectPosition);

  return (
    <>
      <group
        {...props}
        dispose={null}
        onClick={() => {
          toggleActive();
        }}
        onPointerMissed={(e) => {
          e.type === "click" && toggleActive(false);
        }}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <instances.Object ref={objectRef} />
        </group>
      </group>
      {active && (
        <ObjectTransformControls
          object={objectRef.current}
          setLocalPosition={()=>setLocalPosition}
        />
      )}
    </>
  );
}

// useGLTF.preload("/modern_chair-transformed.glb");
