/* eslint-disable react/no-unknown-property */
/* eslint-disable react/no-children-prop */
/* eslint-disable react/prop-types */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Merged, useGLTF } from "@react-three/drei";
import React, { createContext, useContext, useMemo, useRef } from "react";
import { useToggle } from "react-use";
import ObjectTransformControls from "../components/ObjectTransformControls";
import { sceneActions, sceneStateStore } from "../store/sceneData";

const context = createContext();
export function TableFlowersInstances({ children, ...props }) {
  const { nodes } = useGLTF("/table_flowers-transformed.glb");
  const instances = useMemo(
    () => ({
      Flowersmagnoliaflowersmagnolia:
        nodes.flowers_magnolia_003_flowers_magnolia_0,
      Flowersmagnoliaflowersmagnoliabowl:
        nodes.flowers_magnolia_003_flowers_magnolia_bowl_0,
      Flowersmagnoliaflowersmagnoliastem:
        nodes.flowers_magnolia_003_flowers_magnolia_stem_0,
      Flowersmagnoliaflowersmagnoliawater:
        nodes.flowers_magnolia_003_flowers_magnolia_water_0,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function TableFlowers(props) {
  const instances = useContext(context);

  const [active, toggleActive] = useToggle(false);

  const objectRef = useRef();

  return (
    <>
      <group
        {...props}
        dispose={null}
        onClick={(e) => {
          e.stopPropagation();
          // setActiveObject(props.objectId);
          // setActiveChildObject(props.objectId, e.object.uuid);
          // setTransformUpdate(true);
          sceneActions.setActiveObject(props.objectId);
          console.log(e.object.instance.current.material.name)
          sceneActions.setActiveMaterial(
            e.object.instance.current.material.name
          );
          toggleActive(true);
        }}
        onPointerMissed={(e) => {
          e.type === "click" && toggleActive(false);
          sceneActions.removeActiveObject();
          console.log(sceneStateStore);
          // rmActiveObject(props.objectId);
          // setTransformUpdate(false);
        }}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[1, 1, 1]}
        ref={objectRef}
      >
        <group scale={0.005}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <instances.Flowersmagnoliaflowersmagnolia color={props.nodes.flowers_magnolia}/>
            <instances.Flowersmagnoliaflowersmagnoliabowl color={props.nodes.flowers_magnolia_bowl}/>
            <instances.Flowersmagnoliaflowersmagnoliastem color={props.nodes.flowers_magnolia_stem}/>
            <instances.Flowersmagnoliaflowersmagnoliawater color={props.nodes.flowers_magnolia_water}/>
          </group>
        </group>
      </group>
      {active && (
        <ObjectTransformControls
          id={props.objectId}
          object={objectRef.current}
        />
      )}
    </>
  );
}

useGLTF.preload("/table_flowers-transformed.glb");
